# Generated by Django 5.1 on 2024-12-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0003_usersolvedquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
